# Generated by Django 5.2.8 on 2025-11-28 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('products', '0002_alter_products_options_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Payment_option',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='products.order'),
        ),
    ]
